version: "3.9"  # optional since v1.27.0
services:
  auth:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:

  myapp: